Repository aquality-automation/aquality-selenium-core-java, pull requests merged in 2020-02, with the labels that each got.

#28 Feature/13 element finder
  src/main/java/aquality/selenium/core/applications/AqualityModule.java
  src/main/java/aquality/selenium/core/elements/DesiredState.java
  src/main/java/aquality/selenium/core/elements/ElementFinder.java
  src/main/java/aquality/selenium/core/elements/ElementState.java
  src/main/java/aquality/selenium/core/elements/IElementsModule.java
  src/main/java/aquality/selenium/core/elements/RelativeElementFinder.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementFinder.java
  src/test/java/tests/ITestWithApplication.java
  src/test/java/tests/application/IApplicationTests.java
  src/test/java/tests/application/browser/ChromeApplication.java
  src/test/java/tests/application/windowsApp/CalculatorWindow.java
  src/test/java/tests/elements/ElementFinderTests.java
  src/test/java/tests/elements/IElementFinderTests.java
  src/test/java/tests/elements/RelativeElementFinderTests.java
  src/test/java/tests/waitings/BaseConditionalWaitTest.java
  src/test/resources/TestSuite.xml
Labels: Feature

#30 Feature/12 element state provider
  src/main/java/aquality/selenium/core/elements/CachedElementStateProvider.java
  src/main/java/aquality/selenium/core/elements/DefaultElementStateProvider.java
  src/main/java/aquality/selenium/core/elements/ElementCacheHandler.java
  src/main/java/aquality/selenium/core/elements/ElementFinder.java
  src/main/java/aquality/selenium/core/elements/ElementStateProvider.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementCacheHandler.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementStateProvider.java
  src/main/java/aquality/selenium/core/waitings/ConditionalWait.java
  src/main/resources/localization/be.json
  src/main/resources/localization/en.json
  src/main/resources/localization/ru.json
  src/test/java/tests/application/ICachedElement.java
  src/test/java/tests/application/browser/AqualityServices.java
  src/test/java/tests/application/browser/CachedLabel.java
  src/test/java/tests/application/browser/ITheInternetPageTest.java
  src/test/java/tests/application/windowsApp/CachedButton.java
  src/test/java/tests/elements/CachedElementStateProviderTests.java
  src/test/java/tests/elements/CachedWebElementTests.java
  src/test/java/tests/elements/CachedWindowsElementTests.java
  src/test/java/tests/elements/DefaultElementStateProviderTests.java
  src/test/java/tests/elements/ICachedElementTests.java
  src/test/java/tests/elements/IWebElementStateProviderTests.java
  src/test/java/tests/localization/LocalizationManagerTests.java
  src/test/java/tests/utilities/ElementActionRetrierTests.java
  src/test/java/theinternet/BaseForm.java
  src/test/java/theinternet/DynamicControlsForm.java
  src/test/java/theinternet/DynamicLoadingForm.java
  src/test/java/theinternet/TheInternetPage.java
  src/test/java/utils/TimeUtil.java
  src/test/resources/TestSuite.xml
Labels: Feature

#36 Bug/29 fix conditional wait tests
  src/test/java/tests/waitings/BaseConditionalWaitTest.java
  src/test/java/tests/waitings/WaitForObjectTests.java
  src/test/java/tests/waitings/WaitForTests.java
  src/test/java/tests/waitings/WaitForTrueTests.java
  src/test/java/utils/Timer.java
Labels: bug

#35 Fix #22 : JsonSettingsFile should throw an exception
  src/main/java/aquality/selenium/core/utilities/JsonSettingsFile.java
  src/test/java/tests/utilities/SettingsFileTests.java
  src/test/resources/settings.jsontest.json
Labels: bug

#33 Add configurations module
  src/main/java/aquality/selenium/core/applications/AqualityModule.java
  src/main/java/aquality/selenium/core/configurations/IConfigurationsModule.java
  src/main/java/aquality/selenium/core/elements/IElementsModule.java
  src/main/java/aquality/selenium/core/localization/ILocalizationModule.java
Labels: Feature

#37 Enhancement/27 migrate long timeouts to duration
  src/main/java/aquality/selenium/core/applications/IApplication.java
  src/main/java/aquality/selenium/core/configurations/IRetryConfiguration.java
  src/main/java/aquality/selenium/core/configurations/ITimeoutConfiguration.java
  src/main/java/aquality/selenium/core/configurations/RetryConfiguration.java
  src/main/java/aquality/selenium/core/configurations/TimeoutConfiguration.java
  src/main/java/aquality/selenium/core/elements/CachedElementStateProvider.java
  src/main/java/aquality/selenium/core/elements/DefaultElementStateProvider.java
  src/main/java/aquality/selenium/core/elements/Element.java
  src/main/java/aquality/selenium/core/elements/ElementCacheHandler.java
  src/main/java/aquality/selenium/core/elements/ElementFactory.java
  src/main/java/aquality/selenium/core/elements/ElementFinder.java
  src/main/java/aquality/selenium/core/elements/ElementStateProvider.java
  src/main/java/aquality/selenium/core/elements/RelativeElementFinder.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElement.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementCacheHandler.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementFinder.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementStateProvider.java
  src/main/java/aquality/selenium/core/utilities/ElementActionRetrier.java
  src/main/java/aquality/selenium/core/waitings/ConditionalWait.java
  src/main/java/aquality/selenium/core/waitings/IConditionalWait.java
  src/test/java/tests/applications/IApplicationTests.java
  src/test/java/tests/applications/browser/ChromeApplication.java
  src/test/java/tests/applications/windowsApp/WindowsApplication.java
  src/test/java/tests/configurations/ConfigurationTests.java
  src/test/java/tests/configurations/EnvConfigurationTests.java
  src/test/java/tests/elements/ICachedElementTests.java
  src/test/java/tests/elements/IElementFinderTests.java
  src/test/java/tests/elements/IWebElementStateProviderTests.java
  src/test/java/tests/elements/WebElementTests.java
  src/test/java/tests/elements/WindowsElementTests.java
  src/test/java/tests/utilities/ElementActionRetrierTests.java
  src/test/java/tests/waitings/BaseConditionalWaitTest.java
  src/test/java/tests/waitings/WaitForObjectTests.java
  src/test/java/tests/waitings/WaitForTests.java
  src/test/java/tests/waitings/WaitForTrueTests.java
  src/test/java/theinternet/DynamicLoadingForm.java
Labels: enhancement

#39 Fix javadocs errors and warnings
  src/main/java/aquality/selenium/core/elements/interfaces/IElement.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementFactory.java
  src/main/java/aquality/selenium/core/elements/interfaces/IElementFinder.java
  src/main/java/aquality/selenium/core/logging/Logger.java
Labels: bug, documentation
